### ISSUE TITLE
Vue

### ISSUE THREAD

**Issue by mcesar** [roxma/nvim-cm-tern#1]
How to enable this source for .vue files?

**Comment by roxma** [comment]
You mean the `<script>` tag inside `.vue` file?

**Comment by mcesar** [comment]
Yes.
Em dom, 26 de fev de 2017 às 04:22, rox <notifications@github.com> escreveu:

**Comment by roxma** [comment]
@mcesar 
update nvim-completion-manager add see if it's working

**Comment by mcesar** [comment]
No, it isn't. But if I change the line 11 of the file `roxma/nvim-cm-tern/pythonx/cm_sources/cm_tern.py` like bellow, it does:

```
- scopes=['javascript','javascript.jsx'],
+ scopes=['javascript','javascript.jsx','vue'],
```
Do you want I send a pull request?

**Comment by roxma** [comment]
The `scopes` usually match the `:echo &filetype` of your buffer. Since `.vue` is not pure javascript file, it may also contains css, html code.

I would prefer to add it like [this commit](https://github.com/roxma/nvim-completion-manager/commit/29236031b5303bad36ccc864aa663cb8c24a52f4). Which would also enable css completion in style tag for `.vue` file.

Note that I got `&filetype` as `vue.html.javascript.css` on my machine, which depends on the filetype detection plugin being used, 

PRs are welcome. I'm gonna do the update now since it's that simple.

**Comment by mcesar** [comment]
In my machine `:echo &filetype` returns `vue`.

**Comment by roxma** [comment]
I've updated nvim-completion-manager, would you help me test it and confirm that it's working?

**Comment by mcesar** [comment]
It's working, thanks!
